=== vivek-singh87/CricketReplatformApp/CricketReplatformApp/cricket/common/xsd/OfferNotification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://esp.cricket.com/ESP/Namespaces/Notifications/Public/OfferNotification.xsd" targetNamespace="http://esp.cricket.com/ESP/Namespaces/Notifications/Public/OfferNotification.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.3">
	<!-- History -->
	<!-- 07/24/13 Navjeet Suri - Initial relase 1.0.00 -->
	<!-- 08/22/13 Navjeet Suri - 1.0.01 
		Added "id" to the response
	-->
	<!-- 09/16/13 Navjeet Suri - 1.0.02 
		Added Features as complexType under RatePlan
	-->
	<!-- 09/24/13 Navjeet Suri - 1.0.03
		Updated the dateType of price to xs:decimal
	-->
	<!-- Schema structure -->
	<xs:element name="OfferNotification">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RatePlan" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="action" type="xs:string">
								<xs:annotation>
									<xs:documentation>Insert
Update
Delete
Upsert</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>Customer Facing Plan Name </xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="500"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="id" type="xs:string"/>
							<xs:element name="code">
								<xs:annotation>
									<xs:documentation>Rate Plan Code</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="price" type="xs:decimal">
								<xs:annotation>
									<xs:documentation>Plan Price</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="category">
								<xs:annotation>
									<xs:documentation>Plan Category:
V - Voice
D - Data</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="type">
								<xs:annotation>
									<xs:documentation>Plan Type:
PIA AIM
PAYGO
BBMM
Internal
PIA</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="56"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="webGroupCode">
								<xs:annotation>
									<xs:documentation>Used to identify the rate plan on the web channel</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="lifecyclePhase" type="xs:int">
								<xs:annotation>
									<xs:documentation>1 - Current
2 - Supported
3 - Grandfathered
4 - Retired</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="activateDtm" type="xs:dateTime">
								<xs:annotation>
									<xs:documentation>Identifies when the rate plan will be available for commercial sales</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="deactivateDtm" type="xs:dateTime" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Commercial End
Date for sales</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Markets">
								<xs:annotation>
									<xs:documentation>Used to identify which markets the rate plan can be sold in.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Market" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="id" type="xs:int"/>
													<xs:element name="name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="31"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="hoCode">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="3"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Devices" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Device - Rate Plan compatibility</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Device" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="phoneId" type="xs:int"/>
													<xs:element name="phoneCode" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Features" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Feature" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="id" type="xs:int"/>
													<xs:element name="code" type="xs:string">
														<xs:annotation>
															<xs:documentation>Feature code</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="type" type="xs:string">
														<xs:annotation>
															<xs:documentation>Included
Optional
Mandatory</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="price" type="xs:decimal"/>
													<xs:element name="isMandatory" type="xs:boolean"/>
													<xs:element name="groupId" type="xs:int"/>
													<xs:element name="groupName" type="xs:string">
														<xs:annotation>
															<xs:documentation>Grouping of features across multiple lines of service</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== vivek-singh87/CricketReplatformApp/CricketReplatformApp/cricket/common/sampleXMLs/OfferNotification.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:OfferNotification xmlns:p="http://esp.cricket.com/ESP/Namespaces/Notifications/Public/ProductNotification.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://esp.cricket.com/ESP/Namespaces/Notifications/Public/ProductNotification.xsd ../xsd/OfferNotification.xsd ">
  <p:RatePlan>
    <p:action>Insert</p:action>
    <p:name>$70 LTE Android Muve Double Data (10GB)-1</p:name>
    <p:code>LTEMVA11</p:code>
    <p:price>70.00</p:price>
    <p:category>PIA AIM</p:category>
    <p:type>V</p:type>
    <p:webGroupCode>RETIRED</p:webGroupCode>
    <p:lifecyclePhase>1</p:lifecyclePhase>
    <p:activateDtm>2013-07-31T12:00:00</p:activateDtm>
    <p:deactivateDtm>2014-07-31T12:00:00</p:deactivateDtm>
    <p:Markets>
      <p:Market>
        <p:id>11</p:id>
        <p:name>Albuquerque</p:name>
        <p:hoCode>350</p:hoCode>
      </p:Market>
      <p:Market>
        <p:id>12</p:id>
        <p:name>Boise</p:name>
        <p:hoCode>420</p:hoCode>
      </p:Market>
    </p:Markets>
    <p:Devices>
      <p:Device>
        <p:phoneId>0</p:phoneId>
        <p:phoneCode>p:phoneCode</p:phoneCode>
      </p:Device>
    </p:Devices>
  </p:RatePlan>
</p:OfferNotification>
